package mu.buildings.information.system;

import javax.swing.JOptionPane;

/**
 *
 * @author Anthony Quinineza
 */
public class AddBuilding extends javax.swing.JFrame {
    
    
    /** Creates new form AddBuildings */
    public AddBuilding() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_main = new javax.swing.JPanel();
        jPanel_interface = new javax.swing.JPanel();
        jLabel_buildingName = new javax.swing.JLabel();
        jTextField_buildingName = new javax.swing.JTextField();
        jLabel_description = new javax.swing.JLabel();
        jScrollPane_description = new javax.swing.JScrollPane();
        jEditorPane_description = new javax.swing.JEditorPane();
        jLabel4 = new javax.swing.JLabel();
        jSeparator_header = new javax.swing.JSeparator();
        jButton_saveButton = new javax.swing.JButton();
        jButton_clearButton = new javax.swing.JButton();
        jButton_mainmenu = new javax.swing.JButton();
        jLabel_bkg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel_main.setLayout(null);

        jPanel_interface.setBackground(new java.awt.Color(255, 255, 204));
        jPanel_interface.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_interface.setLayout(null);

        jLabel_buildingName.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel_buildingName.setText("Name of building:");
        jPanel_interface.add(jLabel_buildingName);
        jLabel_buildingName.setBounds(80, 100, 200, 40);

        jTextField_buildingName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_buildingName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_interface.add(jTextField_buildingName);
        jTextField_buildingName.setBounds(290, 100, 580, 40);

        jLabel_description.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel_description.setText("Description:");
        jPanel_interface.add(jLabel_description);
        jLabel_description.setBounds(80, 160, 200, 40);

        jEditorPane_description.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jEditorPane_description.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane_description.setViewportView(jEditorPane_description);

        jPanel_interface.add(jScrollPane_description);
        jScrollPane_description.setBounds(290, 160, 580, 230);

        jLabel4.setFont(new java.awt.Font("Corbel Light", 1, 40)); // NOI18N
        jLabel4.setText("Add new building");
        jPanel_interface.add(jLabel4);
        jLabel4.setBounds(50, 20, 320, 50);
        jPanel_interface.add(jSeparator_header);
        jSeparator_header.setBounds(10, 80, 950, 2);

        jButton_saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mu/buildings/information/system/images/Save-icon.png"))); // NOI18N
        jButton_saveButton.setText("Save");
        jButton_saveButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_saveButton.setMaximumSize(new java.awt.Dimension(80, 30));
        jButton_saveButton.setMinimumSize(new java.awt.Dimension(80, 30));
        jButton_saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_saveButtonMouseClicked(evt);
            }
        });
        jPanel_interface.add(jButton_saveButton);
        jButton_saveButton.setBounds(450, 410, 90, 60);

        jButton_clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mu/buildings/information/system/images/erase-128.png"))); // NOI18N
        jButton_clearButton.setText("Clear");
        jButton_clearButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_clearButton.setMaximumSize(new java.awt.Dimension(80, 30));
        jButton_clearButton.setMinimumSize(new java.awt.Dimension(80, 30));
        jButton_clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_clearButtonMouseClicked(evt);
            }
        });
        jPanel_interface.add(jButton_clearButton);
        jButton_clearButton.setBounds(680, 410, 90, 60);

        jButton_mainmenu.setText("main menu");
        jButton_mainmenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_mainmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_mainmenuMouseClicked(evt);
            }
        });
        jPanel_interface.add(jButton_mainmenu);
        jButton_mainmenu.setBounds(710, 30, 160, 20);

        jPanel_main.add(jPanel_interface);
        jPanel_interface.setBounds(160, 120, 970, 500);

        jLabel_bkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mu/buildings/information/system/images/bg2.jpg"))); // NOI18N
        jPanel_main.add(jLabel_bkg);
        jLabel_bkg.setBounds(0, 0, 1280, 720);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_main, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_main, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_clearButtonMouseClicked
       jTextField_buildingName.setText("");
       jEditorPane_description.setText("");
       
    }//GEN-LAST:event_jButton_clearButtonMouseClicked

    private void jButton_saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_saveButtonMouseClicked
       SharedVariables shared = new SharedVariables();
       Core data = new Core();
       
       shared.Bname =  jTextField_buildingName.getText();
       shared.Bdesc =  jEditorPane_description.getText();
       
       if(shared.Bname.equals("")){
           JOptionPane.showMessageDialog(null,"Building's Name is empty");
       }
       else if(shared.Bdesc.equals("")){
           JOptionPane.showMessageDialog(null,"Building's info is empty");
       }
       else{
           
        shared.Bdata = shared.Bname + shared.delimeter + shared.Bdesc;
       
        if(data.create("MUbuildings.info", shared.Bdata)){
            JOptionPane.showMessageDialog(null,"Building's info saved succesfully");
        }
        else{
            JOptionPane.showMessageDialog(null,"There's an error saving the infomation");
        }
      }
    }//GEN-LAST:event_jButton_saveButtonMouseClicked

    private void jButton_mainmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_mainmenuMouseClicked
        new MainInterface().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_mainmenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBuilding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBuilding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBuilding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBuilding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBuilding().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_clearButton;
    private javax.swing.JButton jButton_mainmenu;
    private javax.swing.JButton jButton_saveButton;
    private javax.swing.JEditorPane jEditorPane_description;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_bkg;
    private javax.swing.JLabel jLabel_buildingName;
    private javax.swing.JLabel jLabel_description;
    private javax.swing.JPanel jPanel_interface;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JScrollPane jScrollPane_description;
    private javax.swing.JSeparator jSeparator_header;
    private javax.swing.JTextField jTextField_buildingName;
    // End of variables declaration//GEN-END:variables

}
