package mu.buildings.information.system;

/**
 *
 * @author Anthony Quinineza
 */
public class MainInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_Background_platform = new javax.swing.JPanel();
        jPanel_Menu_Platform = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jButton_Add_Building = new javax.swing.JButton();
        jButton_Manage_Building = new javax.swing.JButton();
        jLabel_Background_Images = new javax.swing.JLabel();

        jFrame1.setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 670, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mu/buildings/information/system/images/mu_bkg1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);

        jPanel_Menu_Platform.setBackground(new java.awt.Color(255, 255, 204));
        jPanel_Menu_Platform.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_Menu_Platform.setForeground(new java.awt.Color(255, 255, 204));
        jPanel_Menu_Platform.setLayout(null);

        jLabel_Title.setFont(new java.awt.Font("Corbel Light", 1, 40)); // NOI18N
        jLabel_Title.setText("MU Buildings Information System");
        jPanel_Menu_Platform.add(jLabel_Title);
        jLabel_Title.setBounds(50, 50, 610, 49);

        jButton_Add_Building.setText("Add new building");
        jButton_Add_Building.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_Add_Building.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Add_BuildingMouseClicked(evt);
            }
        });
        jPanel_Menu_Platform.add(jButton_Add_Building);
        jButton_Add_Building.setBounds(220, 200, 260, 50);

        jButton_Manage_Building.setText("Manage existing buildings");
        jButton_Manage_Building.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_Manage_Building.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Manage_BuildingMouseClicked(evt);
            }
        });
        jPanel_Menu_Platform.add(jButton_Manage_Building);
        jButton_Manage_Building.setBounds(220, 260, 260, 50);

        jLabel_Background_Images.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mu/buildings/information/system/images/mu_bkg1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_Background_platformLayout = new javax.swing.GroupLayout(jPanel_Background_platform);
        jPanel_Background_platform.setLayout(jPanel_Background_platformLayout);
        jPanel_Background_platformLayout.setHorizontalGroup(
            jPanel_Background_platformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Background_platformLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel_Menu_Platform, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel_Background_Images, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel_Background_platformLayout.setVerticalGroup(
            jPanel_Background_platformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Background_platformLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jPanel_Menu_Platform, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel_Background_Images, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Background_platform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Background_platform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Add_BuildingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Add_BuildingMouseClicked
        new AddBuilding().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_Add_BuildingMouseClicked

    private void jButton_Manage_BuildingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Manage_BuildingMouseClicked
        new ManageBuilding().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_Manage_BuildingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("*Windows*".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add_Building;
    private javax.swing.JButton jButton_Manage_Building;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Background_Images;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Background_platform;
    private javax.swing.JPanel jPanel_Menu_Platform;
    // End of variables declaration//GEN-END:variables
}
