package mu.buildings.information.system;

import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anthony Quinineza
 */
public class ManageBuilding extends javax.swing.JFrame {
    SharedVariables share = new SharedVariables();
    Core data = new Core();
    
    /** Creates new form ManageBuilding */
    public ManageBuilding() {
        initComponents();
        updateTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_UpdateMenu = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jButton_editUpdateButton = new javax.swing.JButton();
        jTextField_buildingNameEdit = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane_descriptionEdit = new javax.swing.JEditorPane();
        jLabel_buildingInfo1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel_main = new javax.swing.JPanel();
        jPanel_interface = new javax.swing.JPanel();
        jLabel_title = new javax.swing.JLabel();
        JSeparator_header = new javax.swing.JSeparator();
        jScrollPane_buildingNames = new javax.swing.JScrollPane();
        jTable_buildingNames = new javax.swing.JTable();
        jButton_mainMenu = new javax.swing.JButton();
        jLabel_buildingNameSearch = new javax.swing.JLabel();
        jTextField_buildingNameSearch = new javax.swing.JTextField();
        jButton_search = new javax.swing.JButton();
        jLabel_buildingInfo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane_descriptionDisplay = new javax.swing.JEditorPane();
        jTextField_buildingNameDisplay = new javax.swing.JTextField();
        jButton_updateMenuButton = new javax.swing.JButton();
        jButton_remove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jFrame_UpdateMenu.setLocationByPlatform(true);
        jFrame_UpdateMenu.setMinimumSize(new java.awt.Dimension(700, 700));
        jFrame_UpdateMenu.setSize(new java.awt.Dimension(700, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_editUpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mu/buildings/information/system/images/update icon.png"))); // NOI18N
        jButton_editUpdateButton.setText("Update");
        jButton_editUpdateButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_editUpdateButton.setMaximumSize(new java.awt.Dimension(80, 30));
        jButton_editUpdateButton.setMinimumSize(new java.awt.Dimension(80, 30));
        jButton_editUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_editUpdateButtonMouseClicked(evt);
            }
        });
        jPanel1.add(jButton_editUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 150, 40));

        jTextField_buildingNameEdit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_buildingNameEdit.setBorder(javax.swing.BorderFactory.createTitledBorder("Building name:"));
        jPanel1.add(jTextField_buildingNameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 570, 50));

        jEditorPane_descriptionEdit.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));
        jEditorPane_descriptionEdit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane3.setViewportView(jEditorPane_descriptionEdit);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 570, 230));

        jLabel_buildingInfo1.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel_buildingInfo1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_buildingInfo1.setText("Building info");
        jPanel1.add(jLabel_buildingInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 170, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 650, 10));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("EDIT MENU");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 290, 70));

        org.jdesktop.layout.GroupLayout jFrame_UpdateMenuLayout = new org.jdesktop.layout.GroupLayout(jFrame_UpdateMenu.getContentPane());
        jFrame_UpdateMenu.getContentPane().setLayout(jFrame_UpdateMenuLayout);
        jFrame_UpdateMenuLayout.setHorizontalGroup(
            jFrame_UpdateMenuLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        jFrame_UpdateMenuLayout.setVerticalGroup(
            jFrame_UpdateMenuLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel_main.setLayout(null);

        jPanel_interface.setBackground(new java.awt.Color(255, 255, 204));
        jPanel_interface.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        jPanel_interface.setForeground(new java.awt.Color(255, 255, 204));
        jPanel_interface.setLayout(null);

        jLabel_title.setFont(new java.awt.Font("Corbel Light", 1, 40)); // NOI18N
        jLabel_title.setText("Manage MU buildings");
        jPanel_interface.add(jLabel_title);
        jLabel_title.setBounds(30, 20, 420, 40);
        jPanel_interface.add(JSeparator_header);
        JSeparator_header.setBounds(10, 70, 1200, 2);

        jTable_buildingNames.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable_buildingNames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MU Buildings"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_buildingNames.setRowHeight(60);
        jTable_buildingNames.getTableHeader().setReorderingAllowed(false);
        jScrollPane_buildingNames.setViewportView(jTable_buildingNames);
        if (jTable_buildingNames.getColumnModel().getColumnCount() > 0) {
            jTable_buildingNames.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel_interface.add(jScrollPane_buildingNames);
        jScrollPane_buildingNames.setBounds(720, 80, 490, 570);

        jButton_mainMenu.setText("main menu");
        jButton_mainMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_mainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_mainMenuMouseClicked(evt);
            }
        });
        jPanel_interface.add(jButton_mainMenu);
        jButton_mainMenu.setBounds(1010, 30, 160, 20);

        jLabel_buildingNameSearch.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel_buildingNameSearch.setText("Enter buildings name:");
        jPanel_interface.add(jLabel_buildingNameSearch);
        jLabel_buildingNameSearch.setBounds(10, 100, 230, 40);

        jTextField_buildingNameSearch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_buildingNameSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_interface.add(jTextField_buildingNameSearch);
        jTextField_buildingNameSearch.setBounds(240, 100, 350, 40);

        jButton_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mu/buildings/information/system/images/search button.png"))); // NOI18N
        jButton_search.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_search.setMaximumSize(new java.awt.Dimension(80, 30));
        jButton_search.setMinimumSize(new java.awt.Dimension(80, 30));
        jButton_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_searchMouseClicked(evt);
            }
        });
        jPanel_interface.add(jButton_search);
        jButton_search.setBounds(600, 100, 50, 40);

        jLabel_buildingInfo.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel_buildingInfo.setText("Building info");
        jPanel_interface.add(jLabel_buildingInfo);
        jLabel_buildingInfo.setBounds(40, 160, 160, 40);

        jEditorPane_descriptionDisplay.setEditable(false);
        jEditorPane_descriptionDisplay.setBackground(new java.awt.Color(255, 255, 255));
        jEditorPane_descriptionDisplay.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));
        jEditorPane_descriptionDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(jEditorPane_descriptionDisplay);

        jPanel_interface.add(jScrollPane2);
        jScrollPane2.setBounds(40, 280, 670, 240);

        jTextField_buildingNameDisplay.setEditable(false);
        jTextField_buildingNameDisplay.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_buildingNameDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_buildingNameDisplay.setBorder(javax.swing.BorderFactory.createTitledBorder("Building name:"));
        jPanel_interface.add(jTextField_buildingNameDisplay);
        jTextField_buildingNameDisplay.setBounds(40, 210, 600, 50);

        jButton_updateMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mu/buildings/information/system/images/update icon.png"))); // NOI18N
        jButton_updateMenuButton.setText("Edit");
        jButton_updateMenuButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_updateMenuButton.setMaximumSize(new java.awt.Dimension(80, 30));
        jButton_updateMenuButton.setMinimumSize(new java.awt.Dimension(80, 30));
        jButton_updateMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_updateMenuButtonMouseClicked(evt);
            }
        });
        jPanel_interface.add(jButton_updateMenuButton);
        jButton_updateMenuButton.setBounds(340, 540, 90, 60);

        jButton_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mu/buildings/information/system/images/delete_16x16.gif"))); // NOI18N
        jButton_remove.setText("Remove");
        jButton_remove.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_remove.setMaximumSize(new java.awt.Dimension(80, 30));
        jButton_remove.setMinimumSize(new java.awt.Dimension(80, 30));
        jButton_remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_removeMouseClicked(evt);
            }
        });
        jPanel_interface.add(jButton_remove);
        jButton_remove.setBounds(570, 540, 90, 60);

        jPanel_main.add(jPanel_interface);
        jPanel_interface.setBounds(30, 20, 1220, 680);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mu/buildings/information/system/images/bg2.jpg"))); // NOI18N
        jPanel_main.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_main, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_main, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_updateMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_updateMenuButtonMouseClicked
        if(jTextField_buildingNameDisplay.getText().equals("") || jEditorPane_descriptionDisplay.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Please search the building name first");
        }
        else{
            String Bname = jTextField_buildingNameDisplay.getText();
            String Bdesc = jEditorPane_descriptionDisplay.getText();
            
            jTextField_buildingNameDisplay.setText("");
            jEditorPane_descriptionDisplay.setText("");
            jFrame_UpdateMenu.show();
            
            jTextField_buildingNameEdit.setText(Bname);
            jEditorPane_descriptionEdit.setText(Bdesc);
        }
        
    }//GEN-LAST:event_jButton_updateMenuButtonMouseClicked

    private void jButton_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_searchMouseClicked
        share.bNameSearch = jTextField_buildingNameSearch.getText();
        if(share.bNameSearch.equals("")){
            JOptionPane.showMessageDialog(null,"Please input building name in in the search text field");
        }
        else{
            share.result = data.getData("MUbuildings.info", share.bNameSearch);
            try{
                if(share.result[0] == null){
                    JOptionPane.showMessageDialog(null,"File not found");
                    updateTable();
                }
                else{
                    jTextField_buildingNameDisplay.setText(share.result[0]);
                    jEditorPane_descriptionDisplay.setText(share.result[1]);
                }
            }
            catch(java.lang.ArrayIndexOutOfBoundsException ex){
                updateTable();
            }
        }
    }//GEN-LAST:event_jButton_searchMouseClicked

    private void jButton_mainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_mainMenuMouseClicked
        new MainInterface().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_mainMenuMouseClicked

    private void jButton_removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_removeMouseClicked
        if(share.bNameSearch == null){
            JOptionPane.showMessageDialog(null,"Please search the building name first");
        }else{
            share.confirmDel = JOptionPane.showConfirmDialog(null,"Confirm Delete?");
            if(share.confirmDel == JOptionPane.YES_OPTION){
                
                if(data.delete("MUbuildings.info", share.bNameSearch)){
                    JOptionPane.showMessageDialog(null,"Building " + share.bNameSearch + " and its info has been deleted.");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Delete Failed");
                }
            }
        }
        jTextField_buildingNameDisplay.setText("");
        jEditorPane_descriptionDisplay.setText("");
        updateTable();
    }//GEN-LAST:event_jButton_removeMouseClicked

    private void jButton_editUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_editUpdateButtonMouseClicked

        share.Bname = jTextField_buildingNameEdit.getText();
        share.Bdesc = jEditorPane_descriptionEdit.getText();
        
        if(jTextField_buildingNameEdit.equals("") && jEditorPane_descriptionEdit.equals("")){
            JOptionPane.showMessageDialog(null,"Please input all the following textfield");
        }
        else{
            share.confirmUpdate = JOptionPane.showConfirmDialog(null,"Confirm Update?");
            if(share.confirmUpdate == JOptionPane.YES_OPTION){
                share.Bdata = share.Bname + share.delimeter + share.Bdesc;
                if(data.Edit("MUbuildings.info", share.bNameSearch, share.Bdata)){
                    JOptionPane.showMessageDialog(null,"Building's infomation has been updated.");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Update Failed");
                }
            }
        }
        updateTable();
        jFrame_UpdateMenu.hide();
    }//GEN-LAST:event_jButton_editUpdateButtonMouseClicked
    
    private void updateTable(){
        jTextField_buildingNameSearch.setText("");
        share.bNameSearch = null;
        DefaultTableModel model = (DefaultTableModel) jTable_buildingNames.getModel();
	model.setRowCount(0);
       
	try{
            FileInputStream FileRec = new FileInputStream("MUbuildings.info");
            DataInputStream myInput = new DataInputStream(FileRec);
            
            while(((share.ThisLine = myInput.readLine()) != null)){ 
		share.Rdata = share.ThisLine.split("\\" + share.delimeter);
                
                share.Bname = share.Rdata[0];
                
                Object[] row = {share.Bname};
                model.addRow(row);
            }
	
            myInput.close();
            
	}catch(IOException ex){
            JOptionPane.showMessageDialog(null,"you must create a new building information in Add new buildings tab at the main menu first");
	}
       
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBuilding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBuilding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBuilding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBuilding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBuilding().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator JSeparator_header;
    private javax.swing.JButton jButton_editUpdateButton;
    private javax.swing.JButton jButton_mainMenu;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JButton jButton_search;
    private javax.swing.JButton jButton_updateMenuButton;
    private javax.swing.JEditorPane jEditorPane_descriptionDisplay;
    private javax.swing.JEditorPane jEditorPane_descriptionEdit;
    private javax.swing.JFrame jFrame_UpdateMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_buildingInfo;
    private javax.swing.JLabel jLabel_buildingInfo1;
    private javax.swing.JLabel jLabel_buildingNameSearch;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_interface;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane_buildingNames;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_buildingNames;
    private javax.swing.JTextField jTextField_buildingNameDisplay;
    private javax.swing.JTextField jTextField_buildingNameEdit;
    private javax.swing.JTextField jTextField_buildingNameSearch;
    // End of variables declaration//GEN-END:variables

}
